/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.example.apiserver.objects;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class WagerRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7926238852289359822L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WagerRequest\",\"namespace\":\"com.example.apiserver.objects\",\"fields\":[{\"name\":\"jackpotPoolId\",\"type\":\"string\",\"doc\":\"The ID of a specific Jackpot pool\"},{\"name\":\"wager\",\"type\":\"int\",\"doc\":\"The wager being placed to the Jackpot pool\"}],\"version\":\"1\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<WagerRequest> ENCODER =
      new BinaryMessageEncoder<WagerRequest>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<WagerRequest> DECODER =
      new BinaryMessageDecoder<WagerRequest>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<WagerRequest> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<WagerRequest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<WagerRequest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<WagerRequest>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this WagerRequest to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a WagerRequest from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a WagerRequest instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static WagerRequest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** The ID of a specific Jackpot pool */
  private java.lang.CharSequence jackpotPoolId;
  /** The wager being placed to the Jackpot pool */
  private int wager;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WagerRequest() {}

  /**
   * All-args constructor.
   * @param jackpotPoolId The ID of a specific Jackpot pool
   * @param wager The wager being placed to the Jackpot pool
   */
  public WagerRequest(java.lang.CharSequence jackpotPoolId, java.lang.Integer wager) {
    this.jackpotPoolId = jackpotPoolId;
    this.wager = wager;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return jackpotPoolId;
    case 1: return wager;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: jackpotPoolId = (java.lang.CharSequence)value$; break;
    case 1: wager = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'jackpotPoolId' field.
   * @return The ID of a specific Jackpot pool
   */
  public java.lang.CharSequence getJackpotPoolId() {
    return jackpotPoolId;
  }


  /**
   * Sets the value of the 'jackpotPoolId' field.
   * The ID of a specific Jackpot pool
   * @param value the value to set.
   */
  public void setJackpotPoolId(java.lang.CharSequence value) {
    this.jackpotPoolId = value;
  }

  /**
   * Gets the value of the 'wager' field.
   * @return The wager being placed to the Jackpot pool
   */
  public int getWager() {
    return wager;
  }


  /**
   * Sets the value of the 'wager' field.
   * The wager being placed to the Jackpot pool
   * @param value the value to set.
   */
  public void setWager(int value) {
    this.wager = value;
  }

  /**
   * Creates a new WagerRequest RecordBuilder.
   * @return A new WagerRequest RecordBuilder
   */
  public static com.example.apiserver.objects.WagerRequest.Builder newBuilder() {
    return new com.example.apiserver.objects.WagerRequest.Builder();
  }

  /**
   * Creates a new WagerRequest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new WagerRequest RecordBuilder
   */
  public static com.example.apiserver.objects.WagerRequest.Builder newBuilder(com.example.apiserver.objects.WagerRequest.Builder other) {
    if (other == null) {
      return new com.example.apiserver.objects.WagerRequest.Builder();
    } else {
      return new com.example.apiserver.objects.WagerRequest.Builder(other);
    }
  }

  /**
   * Creates a new WagerRequest RecordBuilder by copying an existing WagerRequest instance.
   * @param other The existing instance to copy.
   * @return A new WagerRequest RecordBuilder
   */
  public static com.example.apiserver.objects.WagerRequest.Builder newBuilder(com.example.apiserver.objects.WagerRequest other) {
    if (other == null) {
      return new com.example.apiserver.objects.WagerRequest.Builder();
    } else {
      return new com.example.apiserver.objects.WagerRequest.Builder(other);
    }
  }

  /**
   * RecordBuilder for WagerRequest instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WagerRequest>
    implements org.apache.avro.data.RecordBuilder<WagerRequest> {

    /** The ID of a specific Jackpot pool */
    private java.lang.CharSequence jackpotPoolId;
    /** The wager being placed to the Jackpot pool */
    private int wager;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.example.apiserver.objects.WagerRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.jackpotPoolId)) {
        this.jackpotPoolId = data().deepCopy(fields()[0].schema(), other.jackpotPoolId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.wager)) {
        this.wager = data().deepCopy(fields()[1].schema(), other.wager);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing WagerRequest instance
     * @param other The existing instance to copy.
     */
    private Builder(com.example.apiserver.objects.WagerRequest other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.jackpotPoolId)) {
        this.jackpotPoolId = data().deepCopy(fields()[0].schema(), other.jackpotPoolId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.wager)) {
        this.wager = data().deepCopy(fields()[1].schema(), other.wager);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'jackpotPoolId' field.
      * The ID of a specific Jackpot pool
      * @return The value.
      */
    public java.lang.CharSequence getJackpotPoolId() {
      return jackpotPoolId;
    }


    /**
      * Sets the value of the 'jackpotPoolId' field.
      * The ID of a specific Jackpot pool
      * @param value The value of 'jackpotPoolId'.
      * @return This builder.
      */
    public com.example.apiserver.objects.WagerRequest.Builder setJackpotPoolId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.jackpotPoolId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'jackpotPoolId' field has been set.
      * The ID of a specific Jackpot pool
      * @return True if the 'jackpotPoolId' field has been set, false otherwise.
      */
    public boolean hasJackpotPoolId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'jackpotPoolId' field.
      * The ID of a specific Jackpot pool
      * @return This builder.
      */
    public com.example.apiserver.objects.WagerRequest.Builder clearJackpotPoolId() {
      jackpotPoolId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'wager' field.
      * The wager being placed to the Jackpot pool
      * @return The value.
      */
    public int getWager() {
      return wager;
    }


    /**
      * Sets the value of the 'wager' field.
      * The wager being placed to the Jackpot pool
      * @param value The value of 'wager'.
      * @return This builder.
      */
    public com.example.apiserver.objects.WagerRequest.Builder setWager(int value) {
      validate(fields()[1], value);
      this.wager = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'wager' field has been set.
      * The wager being placed to the Jackpot pool
      * @return True if the 'wager' field has been set, false otherwise.
      */
    public boolean hasWager() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'wager' field.
      * The wager being placed to the Jackpot pool
      * @return This builder.
      */
    public com.example.apiserver.objects.WagerRequest.Builder clearWager() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public WagerRequest build() {
      try {
        WagerRequest record = new WagerRequest();
        record.jackpotPoolId = fieldSetFlags()[0] ? this.jackpotPoolId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.wager = fieldSetFlags()[1] ? this.wager : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<WagerRequest>
    WRITER$ = (org.apache.avro.io.DatumWriter<WagerRequest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<WagerRequest>
    READER$ = (org.apache.avro.io.DatumReader<WagerRequest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.jackpotPoolId);

    out.writeInt(this.wager);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.jackpotPoolId = in.readString(this.jackpotPoolId instanceof Utf8 ? (Utf8)this.jackpotPoolId : null);

      this.wager = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.jackpotPoolId = in.readString(this.jackpotPoolId instanceof Utf8 ? (Utf8)this.jackpotPoolId : null);
          break;

        case 1:
          this.wager = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










