---
version: '2'
services:
    react:
        image: zachhamilton/rt-jackpot-react:2.0
        hostname: react
        container_name: react
        ports: 
            - 80:80
        environment:
            - "APISERVER=http://localhost:8080"
    apiserver:
        image: zachhamilton/rt-jackpot-apiserver:1.0
        hostname: apiserver
        container_name: apiserver
        ports:
            - 8080:8080
        environment:
            CONFIG_TYPE: "ENV"
            BOOTSTRAP_SERVERS: $BOOTSTRAP_SERVERS
            KAFKA_KEY: $KAFKA_KEY
            KAFKA_SECRET: $KAFKA_SECRET
            SCHEMA_REGISTRY_URL: $SCHEMA_REGISTRY_URL
            SCHEMA_REGISTRY_KEY: $SCHEMA_REGISTRY_KEY
            SCHEMA_REGISTRY_SECRET: $SCHEMA_REGISTRY_SECRET
            KSQL_URL: $KSQL_URL
            KSQL_PORT: 443
            KSQL_KEY: $KSQL_KEY
            KSQL_SECRET: $KSQL_SECRET
      